# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      # run: echo "::set-output name=date::$(date +'%Y%m%d')"
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    # Runs a single command using the runners shell
    - name: Install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        version: latest
    
    - name: Login to docker hub
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      
    # Runs a set of commands using the runners shell
    - name: Build the image
      run: |
        docker buildx build --push \
            --tag ${GITHUB_REPOSITORY}:latest \
            --tag ${GITHUB_REPOSITORY}:${{ steps.vars.outputs.tag }} \
            --platform linux/amd64,linux/arm64 .

    - name: Inspect image
      if: always() && github.event_name != 'pull_request'
      run: |
        docker buildx imagetools inspect ${GITHUB_REPOSITORY}:latest
